<?php

namespace InfoSirene\SDK\Ressources;

class ORIGINE {

    const ORIGINE_VIDE = "";

    const ORIGINE_CREATION = 1;

    const ORIGINE_ACHAT_NON_AGRICOLE = 3;

    const ORIGINE_APPORT_NON_AGRICOLE = 4;

    const ORIGINE_PRISE_LOCATION_GERANCE = 6;

    const ORIGINE_PARTAGE_NON_AGRICOLE = 7;

    const ORIGINE_REPRISE_NON_AGRICOLE = 8;

    const ORIGINE_AUTRE_NON_AGRICOLE = 9;

    const ORIGINE_REPRISE_EXPLOITATION_AGRICOLE = "A";

    const ORIGINE_POURSUITE_EXPLOITATION_PAR_CONJOINT_AGRICOLE = "B";

    const ORIGINE_TRANSFERT_PROPRIETE_AGRICOLE = "C";

    const ORIGINE_APPORT_EXPLOITATION_INDIVIDUELLE_AGRICOLE = "D";

    const ORIGINE_REPRISE_TOTAL_OU_PARTIELLE_EXPLOITATION_INDIVIDUELLE_AGRICOLE = "E";

    const ORIGINE_GERANT_MANDANT = "F";

    const ORIGINE_NON_RENSEIGNE = "NR";



}